version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "factoryopsdb"
      POSTGRES_USER: "factoryops"
      POSTGRES_PASSWORD: "somerandompassword"
    volumes:
      - factory-ops-data:/var/lib/postgresql/data/

volumes:
  factory-ops-data:
